config/routes.rb
Rails.application.routes.draw do
  root 'users#index' 
  get '/users'=>"users#index"
  get "/users/new" =>"users#new",as: :user_new
  post "/users" =>"users#create"
  
  get "/users/sign_in" => "users#sign_in" ,as: :user_sign_in
  post "/users/create_session" =>"users#create_session",as: :create_session
  delete "/users/sign_out" => "users#sign_out" ,as: :user_sign_out
  
  resources :users

end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    # byebug
  	@name = "Alchemy"
  
  	@users = User.all

    # earlier we used cookies, but then that was unsafe
    # if (!cookies[:user_id].blank?)
      # so we used session
    if (!session[:user_id].blank?)
      @name="A"
      @signed_in_user = User.find(session[:user_id])
    end
  end

  def new
  	@user = User.new
  end



  def create
  	User.create(user_params)
   	redirect_to action: 'index'
  end

  def edit
  	@user = User.find(params[:id])
  end

  def update
  	@user = User.find(params[:id].to_i)
  	@user.update(user_params)
  	@user.save
  	redirect_to action: 'index'
  end

  def destroy
  	@user = User.find(params[:id].to_i)
    if(session[:user_id]==@user.id)
       session.delete(:user_id)
    end
  	@user.destroy
  	redirect_to action: 'index'
  end


  def sign_in
    # don't display sign in page in case user is already signed in
    # if (!cookies[:user_id].blank?)
    if (!session[:user_id].blank?)

      redirect_to action: 'index'
    end
  end

  def create_session
    # finding user who has signed in
    user = User.find_by(
      email: params[:email],
      password: params[:password]
      )
    # if user found then set the session variable (earlier we were
      # setting cookies)
    if !user.nil?
      # cookies[:user_id] = user.id
        session[:user_id] = user.id
    end

    redirect_to action: 'index'

  end

  def sign_out
    # removing the key user_id from session hash
    # cookies.delete(:user_id)
    session.delete(:user_id)

    redirect_to action: 'index'
  end



  private
 
  def user_params
     params.require(:user).permit(:First_name,:Surname,:email,:Mobile,:College,:Year,:dob,:password)
  end



end









# ---------------
# class UsersController < ApplicationController
#   def index
#   	@users=User.all
#   	 if (!session[:user_id].blank?)
#       @signed_in_user = User.find(session[:user_id])
#      end

#   end

#   def new
#     @user=User.new 
#   end

#   def create
#   	User.create(user_params)
#   	redirect_to action: 'index'
#   end

#   def sign_in
#   	if(!session[:user_id].blank?)
#   		redirect_to action: 'index'
#   	end

#   end

#   def sign_out
#   	session.delete(:user_id)
#   	redirect_to action: 'index'		
#   end

#   def create_session
#   	user=User.find_by(
#   	  email: params[:Email],
#   	  password: params[:Password]
#   	  )
#     if !user.nil?
#     	session[:user_id]=user.id
#     end
#     redirect_to action: 'index'
#   end

#   private

#   def user_params
#   	 params.require(:user).permit(:First_name,:Surname,:Email,:Mobile,:College,:Year,:dob,:Password)
#   end

# end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TravellingPartners</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for @user do |f|%>
	<%= f.label :First_name %>
	<%= f.text_field :First_name %>
	<br>

	<%= f.label :Surname %>
	<%= f.text_field :Surname %>

	<br>
	<%= f.label :email %>
	<%= f.email_field :email %>
    
    <br>
    <%= f.label :Mobile %>
	<%= f.number_field :Mobile %>

	
 	<br>
	<%= f.label :College %>
	<%= f.text_field :College %>

	<br>
	<%= f.label :Year %>
	<%= f.number_field :Year %>

	<br>
	<%= f.label :Dob %>
	<%= f.date_field :dob %>

	<br>
	<%= f.label :password %>
	<%= f.password_field :password %>



	<br>

	<%= f.submit  :submit%>

<% end %>

app/views/users/create_session.html.erb
<%= @new%>

app/views/users/edit.html.erb
<%="Hey!Edit your info here:"%>
<h6><%= render 'form'%></h6>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

<%=@name%>


<% if !@signed_in_user.blank? %>
	<h1>Signed In User: <%= @signed_in_user.email %></h1>
	<p><%= link_to "Sign Out", user_sign_out_path, method: :delete %></p>
	<p><%= link_to "Edit Account Info",edit_user_path(@signed_in_user.id) %></p>
<%else%>
	<p><%= link_to "Sign In", user_sign_in_path %></p>
	<p><%= link_to "Create Account", user_new_path %></p>
<% end %>


<% @users.each do |u| %>
<%= u.First_name %>
<%end%>

app/views/users/new.html.erb
<h1> Welcome to make yourself a part of the Travelling Partners!<h1>
<h5><%= render 'form' %></h5>

app/views/users/sign_in.html.erb
<%= form_tag create_session_path, method: :post do %>

  <%= label_tag :email%>
  <%= email_field_tag :email%>
  
  <br>

  <%= label_tag :password%>
  <%= password_field_tag :password%>
  
  <br>


  <%= submit_tag "Sign In"%>	



<%end%>